#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace PFE.Editor.Importers.SWF
{
    /// <summary>
    /// Copies body-part PNGs from the JPEXS export, imports them into Unity
    /// with correct PPU and pivot settings derived from SWF shape bounds.
    /// </summary>
    public static class CharacterSpriteImporter
    {
        const int PixelsPerUnit = 100;
        const string CharacterArtRoot = "Assets/_PFE/Art/Character";

        /// <summary>
        /// Import result containing all imported sprites organized by symbol ID and frame.
        /// </summary>
        public class ImportResult
        {
            /// <summary>symbolId → (frameIndex → Sprite). Frame index is 0-based.</summary>
            public Dictionary<int, Dictionary<int, Sprite>> SpritesBySymbol = new();

            /// <summary>symbolId → computed pivot (normalized 0-1).</summary>
            public Dictionary<int, Vector2> PivotsBySymbol = new();

            public int TotalSpritesImported;
            public int TotalSymbolsProcessed;
            public int ZoomFactor = 1;
            public List<string> Warnings = new();
        }

        /// <summary>
        /// Imports all character-related sprites from the JPEXS export folder.
        /// </summary>
        /// <param name="jpexsExportRoot">Path to _assets/ folder with sprites/ subfolder</param>
        /// <param name="swfData">Parsed SWF data for pivot computation</param>
        /// <param name="symbolIds">Set of symbol IDs to import. If null, imports all known body parts.</param>
        /// <param name="extraSymbolIds">Additional symbol IDs to import (e.g. head armor variants). Merged with symbolIds.</param>
        /// <param name="zoomFactor">JPEXS export zoom factor. PNGs exported at Nx zoom need PPU*N to render at correct size.</param>
        public static ImportResult Import(string jpexsExportRoot, SWFFile swfData,
            HashSet<int> symbolIds = null, HashSet<int> extraSymbolIds = null, int zoomFactor = 1)
        {
            var result = new ImportResult();
            result.ZoomFactor = zoomFactor;
            string spritesRoot = Path.Combine(jpexsExportRoot, "sprites");

            if (!Directory.Exists(spritesRoot))
            {
                Debug.LogError($"[CharacterSpriteImporter] Sprites folder not found: {spritesRoot}");
                return result;
            }

            // If no specific IDs given, import individual body parts only.
            // State composites are generated by the Animation Preview tool, not imported from JPEXS.
            if (symbolIds == null)
            {
                symbolIds = new HashSet<int>(AS3StateMapping.BodyPartNames.Keys);
                // Add head internals
                symbolIds.UnionWith(new[] { 199, 220, 233, 235, 237, 239, 240, 273, 31 });
            }

            // Merge extra symbol IDs (head armor variants, etc.)
            if (extraSymbolIds != null && extraSymbolIds.Count > 0)
            {
                symbolIds.UnionWith(extraSymbolIds);
                Debug.Log($"[CharacterSpriteImporter] Added {extraSymbolIds.Count} extra symbols: " +
                    $"[{string.Join(", ", extraSymbolIds.OrderBy(id => id))}]");
            }

            EnsureDirectoryStructure();

            AssetDatabase.StartAssetEditing();
            try
            {
                foreach (int symbolId in symbolIds)
                {
                    string folderName = $"DefineSprite_{symbolId}_symbol{symbolId}";
                    string sourceFolderPath = Path.Combine(spritesRoot, folderName);

                    if (!Directory.Exists(sourceFolderPath))
                    {
                        result.Warnings.Add($"Symbol {symbolId}: source folder not found at {sourceFolderPath}");
                        continue;
                    }

                    var pngFiles = Directory.GetFiles(sourceFolderPath, "*.png")
                        .OrderBy(f => GetFrameNumber(f))
                        .ToArray();

                    if (pngFiles.Length == 0)
                    {
                        result.Warnings.Add($"Symbol {symbolId}: no PNG files found");
                        continue;
                    }

                    string category = CategorizeSymbol(symbolId);
                    string targetFolder = Path.Combine(CharacterArtRoot, category);
                    EnsureDirectory(targetFolder);

                    // Compute pivot from SWF bounds if available.
                    // Priority: Frame1Bounds (per-frame, matches JPEXS PNG) >
                    //           ShapeBounds (exact for DefineShape) >
                    //           Symbol.Bounds (union of all frames, may not match PNG size)
                    Vector2 pivot = new(0.5f, 0.5f); // default center
                    Rect bounds = default;
                    bool hasBounds = false;

                    if (swfData.ShapeBounds.TryGetValue(symbolId, out bounds) && bounds.width > 0 && bounds.height > 0)
                    {
                        hasBounds = true;
                    }
                    else if (swfData.Frame1Bounds.TryGetValue(symbolId, out var f1b) &&
                             f1b.width > 0 && f1b.height > 0)
                    {
                        bounds = f1b;
                        hasBounds = true;
                    }
                    else if (swfData.Symbols.TryGetValue(symbolId, out var sym) &&
                             sym.Bounds.width > 0 && sym.Bounds.height > 0)
                    {
                        bounds = sym.Bounds;
                        hasBounds = true;
                    }

                    if (hasBounds)
                    {
                        // Registration point is (0,0) in Flash local space.
                        // bounds.x = xMin, bounds.y = yMin (Flash coords, Y-down)
                        // Pivot in Unity sprite space: (0,0) at bottom-left, (1,1) at top-right
                        float pivotX = (0f - bounds.x) / bounds.width;
                        // Flash Y is down, Unity Y is up — flip
                        float pivotY = 1f - ((0f - bounds.y) / bounds.height);
                        // Do NOT clamp — registration point can be outside sprite bounds.
                        // Sprite.Create() supports unclamped pivots.
                        // TextureImporter will clamp separately for its own settings.
                        pivot = new Vector2(pivotX, pivotY);
                    }
                    result.PivotsBySymbol[symbolId] = pivot;

                    var spritesByFrame = new Dictionary<int, Sprite>();

                    for (int i = 0; i < pngFiles.Length; i++)
                    {
                        string pngPath = pngFiles[i];
                        int frameNum = GetFrameNumber(pngPath);
                        string partName = GetPartName(symbolId);
                        // Single-frame parts: "base.png"
                        // Multi-frame parts (armor variants): "f001.png", "f002.png", ...
                        string destFileName = pngFiles.Length > 1
                            ? $"f{frameNum:D3}.png"
                            : "base.png";
                        string destAssetPath = Path.Combine(targetFolder, destFileName);

                        // Copy file if not already there or if source is newer
                        string destFullPath = Path.GetFullPath(destAssetPath);
                        if (!File.Exists(destFullPath) ||
                            File.GetLastWriteTimeUtc(pngPath) > File.GetLastWriteTimeUtc(destFullPath))
                        {
                            File.Copy(pngPath, destFullPath, true);
                        }

                        result.TotalSpritesImported++;
                        // Defer sprite reference loading until after AssetDatabase refresh
                        spritesByFrame[frameNum] = null; // placeholder
                    }

                    result.SpritesBySymbol[symbolId] = spritesByFrame;
                    result.TotalSymbolsProcessed++;
                }
            }
            finally
            {
                AssetDatabase.StopAssetEditing();
            }

            AssetDatabase.Refresh();

            // Now set import settings and collect sprite references
            ConfigureImportSettings(result, swfData);

            return result;
        }

        /// <summary>
        /// After AssetDatabase.Refresh(), configure TextureImporter settings
        /// for all imported sprites and collect Sprite references.
        /// </summary>
        static void ConfigureImportSettings(ImportResult result, SWFFile swfData)
        {
            // Snapshot keys to avoid collection-modified-during-enumeration
            var symbolIds = result.SpritesBySymbol.Keys.ToList();
            int effectivePPU = PixelsPerUnit * result.ZoomFactor;

            foreach (int symbolId in symbolIds)
            {
                var frameMap = result.SpritesBySymbol[symbolId];
                string category = CategorizeSymbol(symbolId);
                string targetFolder = Path.Combine(CharacterArtRoot, category);
                int frameCount = frameMap.Count;

                Vector2 pivot = result.PivotsBySymbol.TryGetValue(symbolId, out var p) ? p : new(0.5f, 0.5f);

                var updatedFrames = new Dictionary<int, Sprite>();
                foreach (int frameNum in frameMap.Keys.OrderBy(k => k))
                {
                    string destFileName = frameCount > 1
                        ? $"f{frameNum:D3}.png"
                        : "base.png";
                    string destAssetPath = Path.Combine(targetFolder, destFileName);

                    // Normalize path separators for Unity AssetDatabase
                    destAssetPath = destAssetPath.Replace('\\', '/');

                    var importer = AssetImporter.GetAtPath(destAssetPath) as TextureImporter;
                    if (importer != null)
                    {
                        // Always force settings to ensure correctness after re-import
                        importer.textureType = TextureImporterType.Sprite;
                        importer.spritePixelsPerUnit = effectivePPU;
                        importer.filterMode = FilterMode.Point;
                        importer.textureCompression = TextureImporterCompression.Uncompressed;

                        // Set pivot via TextureImporterSettings
                        // TextureImporter requires 0-1 range, so clamp here only
                        var settings = new TextureImporterSettings();
                        importer.ReadTextureSettings(settings);
                        settings.spriteAlignment = (int)SpriteAlignment.Custom;
                        settings.spritePivot = new Vector2(
                            Mathf.Clamp01(pivot.x),
                            Mathf.Clamp01(pivot.y));
                        importer.SetTextureSettings(settings);

                        // Set sprite atlas tag
                        importer.spritePackingTag = $"Character_{category}";

                        importer.SaveAndReimport();
                    }
                    else
                    {
                        result.Warnings.Add($"Symbol {symbolId} frame {frameNum}: TextureImporter not found at {destAssetPath}");
                    }

                    // Load the sprite reference
                    var sprite = AssetDatabase.LoadAssetAtPath<Sprite>(destAssetPath);
                    if (sprite != null)
                        updatedFrames[frameNum] = sprite;
                    else
                        result.Warnings.Add($"Symbol {symbolId} frame {frameNum}: could not load sprite at {destAssetPath}");
                }

                result.SpritesBySymbol[symbolId] = updatedFrames;
            }
        }

        static void EnsureDirectoryStructure()
        {
            EnsureDirectory(CharacterArtRoot);
        }

        static void EnsureDirectory(string assetPath)
        {
            string fullPath = Path.GetFullPath(assetPath);
            if (!Directory.Exists(fullPath))
                Directory.CreateDirectory(fullPath);
        }

        /// <summary>
        /// Returns a subfolder path like "Body/korpus" or "Wings/lwing".
        /// Each body part gets its own folder for clean organization.
        /// Multi-frame parts (armor variants) keep all frames together.
        /// </summary>
        static string CategorizeSymbol(int symbolId)
        {
            string partName = GetPartName(symbolId);

            // Wings
            if (symbolId is 3640 or 3650)
                return $"Wings/{partName}";

            // Head internals
            if (symbolId is 199 or 220 or 233 or 235 or 237 or 239 or 240 or 273 or 274 or 31)
                return $"Head/{partName}";

            // Hair/mane/tail
            if (symbolId is 136 or 195 or 692 or 734)
                return $"Hair/{partName}";

            // Legs — group front and hind
            if (symbolId is 78 or 101 or 124 or 297)
                return $"Legs/Front/{partName}";
            if (symbolId is 24 or 55 or 319)
                return $"Legs/Hind/{partName}";

            // Torso/neck/pip
            if (symbolId is 159)
                return "Body/korpus";
            if (symbolId is 182)
                return "Body/neck";
            if (symbolId is 513)
                return "Body/pip";

            // Head armor variants (symbol IDs not in known sets go to Head/Variants/)
            // These are per-armor helm, morda, horn sprites from morda_armor(273) frames
            return $"Head/Variants/{partName}";
        }

        static string GetPartName(int symbolId)
        {
            if (AS3StateMapping.BodyPartNames.TryGetValue(symbolId, out string name))
                return name;

            if (AS3StateMapping.StateLabels.ContainsValue(symbolId))
            {
                foreach (var kvp in AS3StateMapping.StateLabels)
                {
                    if (kvp.Value == symbolId)
                        return kvp.Key;
                }
            }

            // Head internals
            return symbolId switch
            {
                199 => "morda_base",
                220 => "eye",
                233 => "forelock",
                235 => "morda_overlay",
                237 => "horn",
                239 => "magic",
                240 => "konec",
                273 => "morda_armor",
                31 => "helm",
                _ => $"symbol{symbolId}"
            };
        }

        static int GetFrameNumber(string pngPath)
        {
            string fileName = Path.GetFileNameWithoutExtension(pngPath);
            if (int.TryParse(fileName, out int num))
                return num;
            return 0;
        }
    }
}
#endif
