#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace PFE.Editor.Importers.SWF
{
    /// <summary>
    /// Copies body-part PNGs from the JPEXS export, imports them into Unity
    /// with correct PPU and pivot settings derived from SWF shape bounds.
    /// </summary>
    public static class CharacterSpriteImporter
    {
        const int PixelsPerUnit = 100;
        const string CharacterArtRoot = "Assets/_PFE/Art/Character";

        /// <summary>
        /// Import result containing all imported sprites organized by symbol ID and frame.
        /// </summary>
        public class ImportResult
        {
            /// <summary>symbolId → (frameIndex → Sprite). Frame index is 0-based.</summary>
            public Dictionary<int, Dictionary<int, Sprite>> SpritesBySymbol = new();

            /// <summary>symbolId → computed pivot (normalized 0-1).</summary>
            public Dictionary<int, Vector2> PivotsBySymbol = new();

            public int TotalSpritesImported;
            public int TotalSymbolsProcessed;
            public int ZoomFactor = 1;
            public List<string> Warnings = new();
        }

        /// <summary>
        /// Imports all character-related sprites from the JPEXS export folder.
        /// </summary>
        /// <param name="jpexsExportRoot">Path to _assets/ folder with sprites/ subfolder</param>
        /// <param name="swfData">Parsed SWF data for pivot computation</param>
        /// <param name="symbolIds">Set of symbol IDs to import. If null, imports all known body parts.</param>
        /// <param name="extraSymbolIds">Additional symbol IDs to import (e.g. head armor variants). Merged with symbolIds.</param>
        /// <param name="zoomFactor">JPEXS export zoom factor. PNGs exported at Nx zoom need PPU*N to render at correct size.</param>
        public static ImportResult Import(string jpexsExportRoot, SWFFile swfData,
            HashSet<int> symbolIds = null, HashSet<int> extraSymbolIds = null, int zoomFactor = 1)
        {
            var result = new ImportResult();
            result.ZoomFactor = zoomFactor;
            string spritesRoot = Path.Combine(jpexsExportRoot, "sprites");

            if (!Directory.Exists(spritesRoot))
            {
                Debug.LogError($"[CharacterSpriteImporter] Sprites folder not found: {spritesRoot}");
                return result;
            }

            // If no specific IDs given, import individual body parts only.
            // State composites are generated by the Animation Preview tool, not imported from JPEXS.
            if (symbolIds == null)
            {
                symbolIds = new HashSet<int>(AS3StateMapping.BodyPartNames.Keys);
                // Add head internals
                symbolIds.UnionWith(new[] { 199, 220, 233, 235, 237, 239, 240, 273, 31 });
            }

            // Merge extra symbol IDs (head armor variants, etc.)
            if (extraSymbolIds != null && extraSymbolIds.Count > 0)
            {
                symbolIds.UnionWith(extraSymbolIds);
                Debug.Log($"[CharacterSpriteImporter] Added {extraSymbolIds.Count} extra symbols: " +
                    $"[{string.Join(", ", extraSymbolIds.OrderBy(id => id))}]");
            }

            EnsureDirectoryStructure();

            AssetDatabase.StartAssetEditing();
            try
            {
                foreach (int symbolId in symbolIds)
                {
                    string folderName = $"DefineSprite_{symbolId}_symbol{symbolId}";
                    string sourceFolderPath = Path.Combine(spritesRoot, folderName);

                    if (!Directory.Exists(sourceFolderPath))
                    {
                        result.Warnings.Add($"Symbol {symbolId}: source folder not found at {sourceFolderPath}");
                        continue;
                    }

                    var pngFiles = Directory.GetFiles(sourceFolderPath, "*.png")
                        .OrderBy(f => GetFrameNumber(f))
                        .ToArray();

                    if (pngFiles.Length == 0)
                    {
                        result.Warnings.Add($"Symbol {symbolId}: no PNG files found");
                        continue;
                    }

                    string category = CategorizeSymbol(symbolId);
                    string targetFolder = Path.Combine(CharacterArtRoot, category);
                    EnsureDirectory(targetFolder);

                    // Compute pivot from SWF bounds if available.
                    // Priority: Frame1Bounds (per-frame, matches JPEXS PNG) >
                    //           ShapeBounds (exact for DefineShape) >
                    //           Symbol.Bounds (union of all frames, may not match PNG size)
                    Vector2 pivot = new(0.5f, 0.5f); // default center
                    Rect bounds = default;
                    bool hasBounds = false;

                    if (swfData.ShapeBounds.TryGetValue(symbolId, out bounds) && bounds.width > 0 && bounds.height > 0)
                    {
                        hasBounds = true;
                    }
                    else if (swfData.Frame1Bounds.TryGetValue(symbolId, out var f1b) &&
                             f1b.width > 0 && f1b.height > 0)
                    {
                        bounds = f1b;
                        hasBounds = true;
                    }
                    else if (swfData.Symbols.TryGetValue(symbolId, out var sym) &&
                             sym.Bounds.width > 0 && sym.Bounds.height > 0)
                    {
                        bounds = sym.Bounds;
                        hasBounds = true;
                    }

                    if (hasBounds)
                    {
                        // Registration point is (0,0) in Flash local space.
                        // bounds.x = xMin, bounds.y = yMin (Flash coords, Y-down)
                        // Pivot in Unity sprite space: (0,0) at bottom-left, (1,1) at top-right
                        float pivotX = (0f - bounds.x) / bounds.width;
                        // Flash Y is down, Unity Y is up — flip
                        float pivotY = 1f - ((0f - bounds.y) / bounds.height);
                        // Do NOT clamp — registration point can be outside sprite bounds.
                        // Sprite.Create() supports unclamped pivots.
                        // TextureImporter will clamp separately for its own settings.
                        pivot = new Vector2(pivotX, pivotY);
                    }
                    result.PivotsBySymbol[symbolId] = pivot;

                    var spritesByFrame = new Dictionary<int, Sprite>();

                    for (int i = 0; i < pngFiles.Length; i++)
                    {
                        string pngPath = pngFiles[i];
                        int frameNum = GetFrameNumber(pngPath);
                        string partName = GetPartName(symbolId);
                        // Single-frame parts: "base.png"
                        // Multi-frame parts (armor variants): "f001.png", "f002.png", ...
                        string destFileName = pngFiles.Length > 1
                            ? $"f{frameNum:D3}.png"
                            : "base.png";
                        string destAssetPath = Path.Combine(targetFolder, destFileName);

                        // Copy file if not already there or if source is newer
                        string destFullPath = Path.GetFullPath(destAssetPath);
                        if (!File.Exists(destFullPath) ||
                            File.GetLastWriteTimeUtc(pngPath) > File.GetLastWriteTimeUtc(destFullPath))
                        {
                            File.Copy(pngPath, destFullPath, true);
                        }

                        result.TotalSpritesImported++;
                        // Defer sprite reference loading until after AssetDatabase refresh
                        spritesByFrame[frameNum] = null; // placeholder
                    }

                    result.SpritesBySymbol[symbolId] = spritesByFrame;
                    result.TotalSymbolsProcessed++;
                }
            }
            finally
            {
                AssetDatabase.StopAssetEditing();
            }

            AssetDatabase.Refresh();

            // Now set import settings and collect sprite references
            ConfigureImportSettings(result, swfData);

            return result;
        }

        /// <summary>
        /// Extra batched repair rounds for a <c>.meta</c> Unity failed to write. Configurable.
        /// </summary>
        public static int RepairAttempts = 3;

        /// <summary>
        /// Pause between repair rounds, in milliseconds. Retry-only, not per-asset: it blocks the editor's
        /// main thread, so keep it small. 0 disables the pause.
        /// </summary>
        public static int RepairDelayMs = 150;

        /// <summary>
        /// After AssetDatabase.Refresh(), configure TextureImporter settings
        /// for all imported sprites and collect Sprite references.
        ///
        /// <para><b>Three passes, deliberately.</b> The obvious shape — walk the frames and call
        /// <c>SaveAndReimport()</c> on each — is what silently lost thousands of pivots in the weapon
        /// importer on 10-05. Unity 6 imports asynchronously, so a per-asset save collides with the import
        /// it just started: <c>Cannot open file '…meta' for write</c>, then <c>Failed to write meta
        /// file</c>, and the pivot stays at the default with no exception raised. Setting every importer
        /// inside ONE <c>StartAssetEditing</c>/<c>StopAssetEditing</c> batch defers them into a single
        /// ordered flush, so the collision cannot arise. The price is that nothing is loadable until the
        /// batch closes — hence pass 1 sets, pass 2 reads back.</para>
        /// </summary>
        static void ConfigureImportSettings(ImportResult result, SWFFile swfData)
        {
            // Snapshot keys to avoid collection-modified-during-enumeration
            var symbolIds = result.SpritesBySymbol.Keys.ToList();
            int effectivePPU = PixelsPerUnit * result.ZoomFactor;

            // ── Pass 1: set every importer inside a single batch ──────────────
            AssetDatabase.StartAssetEditing();
            try
            {
                foreach (int symbolId in symbolIds)
                {
                    var frameMap = result.SpritesBySymbol[symbolId];
                    string category = CategorizeSymbol(symbolId);
                    string targetFolder = Path.Combine(CharacterArtRoot, category);
                    Vector2 pivot = ClampPivot(PivotFor(result, symbolId));

                    foreach (int frameNum in frameMap.Keys)
                    {
                        string destAssetPath = FrameAssetPath(targetFolder, frameMap.Count, frameNum);

                        if (AssetImporter.GetAtPath(destAssetPath) is TextureImporter importer)
                            ApplySettings(importer, effectivePPU, category, pivot);
                        else
                            result.Warnings.Add($"Symbol {symbolId} frame {frameNum}: TextureImporter not found at {destAssetPath}");
                    }
                }
            }
            finally
            {
                AssetDatabase.StopAssetEditing();   // one import pass over everything we touched
            }

            // ── Pass 2: verify each .meta landed ON DISK, collect stragglers, load ──
            //
            // Verified against the file, not the importer: Unity updates the in-memory copy even when the
            // write to disk failed, so the importer cannot answer "did it persist?".
            var failures = new List<(string assetPath, Vector2 pivot, int ppu, string category)>();
            foreach (int symbolId in symbolIds)
            {
                var frameMap = result.SpritesBySymbol[symbolId];
                string category = CategorizeSymbol(symbolId);
                string targetFolder = Path.Combine(CharacterArtRoot, category);
                Vector2 pivot = ClampPivot(PivotFor(result, symbolId));

                var updatedFrames = new Dictionary<int, Sprite>();
                foreach (int frameNum in frameMap.Keys.OrderBy(k => k))
                {
                    string destAssetPath = FrameAssetPath(targetFolder, frameMap.Count, frameNum);

                    if (!MetaFileHasPivot(destAssetPath, pivot))
                        failures.Add((destAssetPath, pivot, effectivePPU, category));

                    // Load the sprite reference
                    var sprite = AssetDatabase.LoadAssetAtPath<Sprite>(destAssetPath);
                    if (sprite != null)
                        updatedFrames[frameNum] = sprite;
                    else
                        result.Warnings.Add($"Symbol {symbolId} frame {frameNum}: could not load sprite at {destAssetPath}");
                }

                result.SpritesBySymbol[symbolId] = updatedFrames;
            }

            // ── Pass 3: repair the stragglers in BATCHES, pausing between rounds ──
            for (int round = 0; round < RepairAttempts && failures.Count > 0; round++)
            {
                if (round > 0 && RepairDelayMs > 0)
                    System.Threading.Thread.Sleep(RepairDelayMs);   // let Unity's in-flight import settle

                AssetDatabase.StartAssetEditing();
                try
                {
                    foreach (var (assetPath, pivot, ppu, category) in failures)
                    {
                        if (AssetImporter.GetAtPath(assetPath) is not TextureImporter importer) continue;

                        ApplySettings(importer, ppu, category, pivot);

                        // Applying the settings is NOT enough on its own. Unity caches the importer in
                        // memory, and for a frame whose earlier write failed the cached pivot is ALREADY
                        // the target — so SetTextureSettings is a no-op, the asset is never marked dirty,
                        // and no import (hence no .meta write) is ever queued. The forced import is what
                        // actually makes Unity re-serialise the .meta.
                        AssetDatabase.ImportAsset(assetPath, ImportAssetOptions.ForceUpdate);
                    }
                }
                finally
                {
                    AssetDatabase.StopAssetEditing();
                }

                failures.RemoveAll(f => MetaFileHasPivot(f.assetPath, f.pivot));
            }

            foreach (var (assetPath, pivot, _, _) in failures)
                result.Warnings.Add($"Pivot did not persist for {assetPath} (wanted " +
                                    $"{pivot.x:0.####}, {pivot.y:0.####}) — Unity could not write the .meta.");
        }

        static Vector2 PivotFor(ImportResult result, int symbolId)
            => result.PivotsBySymbol.TryGetValue(symbolId, out var p) ? p : new Vector2(0.5f, 0.5f);

        /// <summary>Unity's pivot range is 0-1, so clamp here and only here.</summary>
        static Vector2 ClampPivot(Vector2 pivot)
            => new Vector2(Mathf.Clamp01(pivot.x), Mathf.Clamp01(pivot.y));

        static string FrameAssetPath(string folder, int frameCount, int frameNum)
            => Path.Combine(folder, frameCount > 1 ? $"f{frameNum:D3}.png" : "base.png").Replace('\\', '/');

        static void ApplySettings(TextureImporter importer, int effectivePPU, string category, Vector2 pivot)
        {
            importer.textureType = TextureImporterType.Sprite;
            importer.spritePixelsPerUnit = effectivePPU;
            importer.filterMode = FilterMode.Point;
            importer.textureCompression = TextureImporterCompression.Uncompressed;

            var settings = new TextureImporterSettings();
            importer.ReadTextureSettings(settings);
            settings.spriteAlignment = (int)SpriteAlignment.Custom;
            settings.spritePivot = pivot;
            importer.SetTextureSettings(settings);

            // Set sprite atlas tag
            importer.spritePackingTag = $"Character_{category}";
        }

        /// <summary>
        /// True when the asset's <c>.meta</c> on disk records <paramref name="pivot"/> as the sprite pivot.
        ///
        /// <para>Reads the file rather than the importer on purpose: <see cref="TextureImporter"/> exposes
        /// Unity's in-memory state, which is updated even when the write to disk failed, so it cannot be
        /// used either to decide whether a write is needed or to confirm one succeeded.</para>
        /// </summary>
        static bool MetaFileHasPivot(string assetPath, Vector2 pivot)
        {
            string metaPath = Path.GetFullPath(assetPath) + ".meta";
            if (!File.Exists(metaPath)) return false;

            try
            {
                foreach (string line in File.ReadLines(metaPath))
                {
                    // Top-level "spritePivot: {x: .., y: ..}". Sub-sprite entries inside a spriteSheet are
                    // spelled "pivot:" alone, so this cannot accidentally match one of those.
                    int key = line.IndexOf("spritePivot:", StringComparison.Ordinal);
                    if (key < 0) continue;

                    string body = line.Substring(key + "spritePivot:".Length);
                    int xs = body.IndexOf("x:", StringComparison.Ordinal);
                    int ys = body.IndexOf("y:", StringComparison.Ordinal);
                    if (xs < 0 || ys < 0) return false;

                    int comma = body.IndexOf(',', xs);
                    if (comma < 0) return false;

                    string sx = body.Substring(xs + 2, comma - (xs + 2)).Trim();
                    string sy = body.Substring(ys + 2).Trim().TrimEnd('}').Trim();

                    if (float.TryParse(sx, NumberStyles.Float, CultureInfo.InvariantCulture, out float px) &&
                        float.TryParse(sy, NumberStyles.Float, CultureInfo.InvariantCulture, out float py))
                        return Mathf.Abs(px - pivot.x) < 0.001f && Mathf.Abs(py - pivot.y) < 0.001f;

                    return false;
                }
            }
            catch (Exception)
            {
                // Unreadable or vanished file: treat as "not on disk" so the caller (re)writes it.
            }
            return false;
        }

        static void EnsureDirectoryStructure()
        {
            EnsureDirectory(CharacterArtRoot);
        }

        static void EnsureDirectory(string assetPath)
        {
            string fullPath = Path.GetFullPath(assetPath);
            if (!Directory.Exists(fullPath))
                Directory.CreateDirectory(fullPath);
        }

        /// <summary>
        /// Returns a subfolder path like "Body/korpus" or "Wings/lwing".
        /// Each body part gets its own folder for clean organization.
        /// Multi-frame parts (armor variants) keep all frames together.
        /// </summary>
        static string CategorizeSymbol(int symbolId)
        {
            string partName = GetPartName(symbolId);

            // Wings
            if (symbolId is 3640 or 3650)
                return $"Wings/{partName}";

            // Overlay clips — the siblings of the body sprite (vis.shit). They get their own root
            // rather than a body folder because they are not parts of the body composition, and
            // without this branch they would land in the Head/Variants/ fallback below, which is
            // where every unrecognised symbol goes.
            if (symbolId is 3625)
                return $"Overlays/{partName}";

            // Head internals
            if (symbolId is 199 or 220 or 233 or 235 or 237 or 239 or 240 or 273 or 274 or 31)
                return $"Head/{partName}";

            // Hair/mane/tail
            if (symbolId is 136 or 195 or 692 or 734)
                return $"Hair/{partName}";

            // Legs — group front and hind
            if (symbolId is 78 or 101 or 124 or 297)
                return $"Legs/Front/{partName}";
            if (symbolId is 24 or 55 or 319)
                return $"Legs/Hind/{partName}";

            // Torso/neck/pip
            if (symbolId is 159)
                return "Body/korpus";
            if (symbolId is 182)
                return "Body/neck";
            if (symbolId is 513)
                return "Body/pip";

            // Head armor variants (symbol IDs not in known sets go to Head/Variants/)
            // These are per-armor helm, morda, horn sprites from morda_armor(273) frames
            return $"Head/Variants/{partName}";
        }

        static string GetPartName(int symbolId)
        {
            if (AS3StateMapping.BodyPartNames.TryGetValue(symbolId, out string name))
                return name;

            if (AS3StateMapping.StateLabels.ContainsValue(symbolId))
            {
                foreach (var kvp in AS3StateMapping.StateLabels)
                {
                    if (kvp.Value == symbolId)
                        return kvp.Key;
                }
            }

            // Head internals
            return symbolId switch
            {
                199 => "morda_base",
                220 => "eye",
                233 => "forelock",
                235 => "morda_overlay",
                237 => "horn",
                239 => "magic",
                240 => "konec",
                273 => "morda_armor",
                31 => "helm",
                _ => $"symbol{symbolId}"
            };
        }

        static int GetFrameNumber(string pngPath)
        {
            string fileName = Path.GetFileNameWithoutExtension(pngPath);
            if (int.TryParse(fileName, out int num))
                return num;
            return 0;
        }
    }
}
#endif
