using System;
using System.Collections.Generic;
using UnityEngine;

namespace PFE.Character
{
    /// <summary>
    /// Holds references to imported style layer sprites for character customization.
    /// Each entry maps a (partName, layerName, styleIndex) triple to a Sprite.
    ///
    /// Generated by the CharacterStyleLayerImporter, consumed by CharacterSpriteAssembler.
    ///
    /// Structure matches the import output:
    ///   Mane/Primary/style_1..5
    ///   Mane/Secondary/style_1..5
    ///   Tail/Primary/style_1..5
    ///   Tail/Secondary/style_1..5
    ///   Forelock/Primary/style_1..5
    ///   Forelock/Secondary/style_1..5
    ///   Eye/Iris/style_1..6
    ///   Eye/Pupil/base (optional)
    /// </summary>
    [CreateAssetMenu(fileName = "CharacterStyleData", menuName = "PFE/Character Style Data")]
    public class CharacterStyleData : ScriptableObject
    {
        [Header("Style Layers")]
        public StyleLayerGroup[] layers = Array.Empty<StyleLayerGroup>();

        /// <summary>Lookup built on first access.</summary>
        Dictionary<string, Sprite[]> _lookup;

        /// <summary>
        /// Get a sprite for a specific part, layer, and style index.
        /// Returns null if not found.
        /// </summary>
        /// <param name="partName">e.g. "Mane", "Tail", "Forelock", "Eye"</param>
        /// <param name="layerName">e.g. "Primary", "Secondary", "Iris", "Pupil"</param>
        /// <param name="styleIndex">0-based style index</param>
        public Sprite GetLayerSprite(string partName, string layerName, int styleIndex)
        {
            EnsureLookup();
            string key = $"{partName}/{layerName}";
            if (!_lookup.TryGetValue(key, out var sprites))
                return null;
            if (styleIndex < 0 || styleIndex >= sprites.Length)
                return null;
            return sprites[styleIndex];
        }

        /// <summary>
        /// Get all style sprites for a part/layer combo.
        /// Returns null if not found.
        /// </summary>
        public Sprite[] GetLayerSprites(string partName, string layerName)
        {
            EnsureLookup();
            _lookup.TryGetValue($"{partName}/{layerName}", out var sprites);
            return sprites;
        }

        /// <summary>
        /// Get the number of style variants for a part/layer.
        /// </summary>
        public int GetStyleCount(string partName, string layerName)
        {
            var sprites = GetLayerSprites(partName, layerName);
            return sprites?.Length ?? 0;
        }

        void EnsureLookup()
        {
            if (_lookup != null) return;
            _lookup = new Dictionary<string, Sprite[]>();
            foreach (var group in layers)
            {
                string key = $"{group.partName}/{group.layerName}";
                _lookup[key] = group.sprites ?? Array.Empty<Sprite>();
            }
        }

        void OnEnable()
        {
            _lookup = null; // rebuild on asset reload
        }
    }

    /// <summary>
    /// One group of style sprites for a specific part + layer combination.
    /// </summary>
    [Serializable]
    public class StyleLayerGroup
    {
        [Tooltip("Part name matching CharacterStyleLayerImporter output (Mane, Tail, Forelock, Eye)")]
        public string partName;

        [Tooltip("Layer name (Primary, Secondary, Iris, Pupil)")]
        public string layerName;

        [Tooltip("Tint channel index (0=Fur, 1=Hair, 2=Hair2, 3=Eye, 4=Magic, -1=None)")]
        public int tintChannel = -1;

        [Tooltip("Style variant sprites in order (index 0 = style 1)")]
        public Sprite[] sprites = Array.Empty<Sprite>();
    }
}
