using System;
using System.Collections.Generic;
using UnityEngine;
using PFE.ModAPI;
#if ODIN_INSPECTOR
using Sirenix.OdinInspector;
#endif

namespace PFE.Data.Definitions
{
    /// <summary>
    /// Root ScriptableObject containing all animation data for a character type.
    /// Generated by the SWF Character Importer, consumed at runtime by the animation controller.
    /// </summary>
    [CreateAssetMenu(fileName = "NewCharacterAnimation", menuName = "PFE/Character Animation Definition")]
    public class CharacterAnimationDefinition : ScriptableObject, IGameContent
    {
        [Header("Character Info")]
        public string characterId = "player";

        // IGameContent
        string IGameContent.ContentId => characterId;
        ContentType IGameContent.ContentType => ContentType.CharacterAnimation;
        public float frameRate = 30f;

        [Header("Body Parts")]
        public CharacterPartDefinition[] parts = Array.Empty<CharacterPartDefinition>();

        [Header("Animation States")]
        public CharacterStateClip[] stateClips = Array.Empty<CharacterStateClip>();

        [Header("Armor Overrides")]
        public ArmorVisualSet[] armorSets = Array.Empty<ArmorVisualSet>();

        [Header("Overlay Clips")]
        public CharacterOverlayDefinition[] overlays = Array.Empty<CharacterOverlayDefinition>();

        [Header("Style Options")]
        public int hairStyleCount = 5;
        public int eyeStyleCount = 6;

        /// <summary>Lookup helpers built on first access.</summary>
        Dictionary<string, CharacterStateClip> _stateClipLookup;
        Dictionary<string, CharacterPartDefinition> _partLookup;
        Dictionary<string, ArmorVisualSet> _armorLookup;
        Dictionary<string, CharacterOverlayDefinition> _overlayLookup;

        public CharacterStateClip GetStateClip(string stateName)
        {
            if (_stateClipLookup == null)
            {
                _stateClipLookup = new Dictionary<string, CharacterStateClip>();
                foreach (var clip in stateClips)
                    _stateClipLookup[clip.stateName] = clip;
            }
            _stateClipLookup.TryGetValue(stateName, out var result);
            return result;
        }

        public CharacterPartDefinition GetPart(string partName)
        {
            if (_partLookup == null)
            {
                _partLookup = new Dictionary<string, CharacterPartDefinition>();
                foreach (var part in parts)
                    _partLookup[part.partName] = part;
            }
            _partLookup.TryGetValue(partName, out var result);
            return result;
        }

        public ArmorVisualSet GetArmorSet(string armorId)
        {
            if (_armorLookup == null)
            {
                _armorLookup = new Dictionary<string, ArmorVisualSet>();
                foreach (var set in armorSets)
                    _armorLookup[set.armorId] = set;
            }
            _armorLookup.TryGetValue(armorId, out var result);
            return result;
        }

        public CharacterOverlayDefinition GetOverlay(string overlayName)
        {
            if (_overlayLookup == null)
            {
                _overlayLookup = new Dictionary<string, CharacterOverlayDefinition>();
                foreach (var overlay in overlays)
                    _overlayLookup[overlay.overlayName] = overlay;
            }
            _overlayLookup.TryGetValue(overlayName, out var result);
            return result;
        }

        void OnEnable()
        {
            // Clear cached lookups when asset reloads
            _stateClipLookup = null;
            _partLookup = null;
            _armorLookup = null;
            _overlayLookup = null;
        }
    }

    /// <summary>
    /// Definition of a single body part in the character composition.
    /// </summary>
    [Serializable]
    public class CharacterPartDefinition
    {
        public string partName;
        public int symbolId;
        public int sortOrder;
        public TintCategory tintCategory = TintCategory.None;
        public bool isArmorAware;

        /// <summary>
        /// Base sprite for this part (no armor).
        /// For parts with style variants (hair, eyes), this is the default.
        /// </summary>
        public Sprite baseSprite;

        /// <summary>Style variant sprites (e.g. 5 hair styles). Null if no variants.</summary>
        public Sprite[] styleVariants;

        /// <summary>
        /// Pivot offset from top-left of the sprite to the registration point, normalized 0-1.
        /// Used to reconstruct correct positioning.
        /// </summary>
        public Vector2 pivotNormalized = new(0.5f, 0.5f);
    }

    /// <summary>
    /// A clip that sits on the character's visual container and runs on its <b>own</b> timeline,
    /// independent of the character's state clip.
    ///
    /// <para><b>Why this is not a <see cref="CharacterPartDefinition"/>.</b> In AS3 the character's
    /// container (<c>visualPlayer</c>, symbol 3690) holds one body sprite plus a set of sibling clips
    /// (<c>visualPlayer.as:7-27</c>):</para>
    ///
    /// <code>
    /// public var cryst:MovieClip;   public var fetter:MovieClip;  public var inh:MovieClip;
    /// public var osn:MovieClip;     public var rat:MovieClip;     public var shit:visShit;   public var svet:MovieClip;
    /// </code>
    ///
    /// <para><c>osn</c> is the body — the thing the wing parts (<c>vis.osn.body.lwing</c>) live inside.
    /// <c>shit</c> is a <i>sibling</i> of it, not a part of it, and it is the only one with a class of its
    /// own (<c>visShit</c>). It animates while the body holds still: <c>UnitPlayer.as:4916-4919</c> runs
    /// <c>gotoAndPlay(1)</c> when <c>shithp</c> goes positive and <c>gotoAndStop(1)</c> when it reaches
    /// zero. A body part cannot express that — <see cref="CharacterPartDefinition"/> carries a single
    /// <c>baseSprite</c> with no timeline of its own.</para>
    /// </summary>
    [Serializable]
    public class CharacterOverlayDefinition
    {
        /// <summary>
        /// Overlay id, matching the AS3 clip name — <c>"shit"</c> for <c>vis.shit</c>. This is the key
        /// <c>CharacterVisualContext.IsOverlayVisible</c> gates on, so the two must agree.
        /// </summary>
        public string overlayName;

        /// <summary>
        /// The clip's frames in timeline order. All of them are kept: unlike a body part, whose
        /// <c>baseSprite</c> is frame 1, an overlay plays through this list.
        /// </summary>
        public Sprite[] frames = Array.Empty<Sprite>();

        /// <summary>Pivot of every frame, normalized 0-1, from the SWF registration point.</summary>
        public Vector2 pivotNormalized = new(0.5f, 0.5f);

        /// <summary>Offset from the character origin, in local units.</summary>
        public Vector2 localPosition;

        /// <summary>Uniform scale. The oracle scales the boss shield variants to 1.5-1.7.</summary>
        public float localScale = 1f;

        /// <summary>
        /// Sorting order for the overlay renderer. Must exceed the body's, which is
        /// <c>2 * maxPartPlacements + 1</c> — see <c>CharacterSpriteAssembler</c>.
        /// </summary>
        public int sortingOrder = 1000;

        /// <summary>
        /// What the playhead does at the last frame. The shield holds on its final frame
        /// (<c>ClampForever</c>), because <c>visShit</c>'s frame script calls <c>stop()</c> on frame 20.
        /// </summary>
        public AnimationLoopMode loopMode = AnimationLoopMode.ClampForever;
    }

    /// <summary>
    /// One animation state (e.g. "run") with per-frame placement data for all parts.
    /// </summary>
    [Serializable]
    public class CharacterStateClip
    {
        public string stateName;
        public int frameCount;
        public AnimationLoopMode loopMode = AnimationLoopMode.Loop;

        /// <summary>Loop start frame (0-based). For states that loop a sub-range.</summary>
        public int loopStartFrame;

        /// <summary>Loop end frame (0-based, exclusive). -1 means use frameCount.</summary>
        public int loopEndFrame = -1;

        /// <summary>Per-frame data. Array length = frameCount.</summary>
        public CharacterFrameData[] frames = Array.Empty<CharacterFrameData>();

        /// <summary>
        /// Whether this state uses the run mane/tail variants instead of idle.
        /// </summary>
        public bool useRunMane;
        public bool useRunTail;

        public int EffectiveLoopEnd => loopEndFrame < 0 ? frameCount : loopEndFrame;
    }

    /// <summary>
    /// All part placements for a single frame of an animation state.
    /// </summary>
    [Serializable]
    public class CharacterFrameData
    {
        /// <summary>Per-part placement data for this frame.</summary>
        public PartFramePlacement[] partPlacements = Array.Empty<PartFramePlacement>();
    }

    /// <summary>
    /// Where a specific body part is positioned on a specific frame.
    /// </summary>
    [Serializable]
    public struct PartFramePlacement
    {
        /// <summary>Index into CharacterAnimationDefinition.parts array.</summary>
        public int partIndex;

        /// <summary>Local position relative to character root, in Unity coordinates (Y-up).</summary>
        public Vector2 localPosition;

        /// <summary>Local rotation in degrees (Unity convention, counter-clockwise positive).</summary>
        public float localRotation;

        /// <summary>Local scale.</summary>
        public Vector2 localScale;

        /// <summary>Whether this part is visible on this frame.</summary>
        public bool visible;
    }

    /// <summary>
    /// Armor visual overrides for a specific armor ID.
    /// </summary>
    [Serializable]
    public class ArmorVisualSet
    {
        public string armorId;
        public bool hidesMane;

        /// <summary>Per-part armor sprites. Only populated for armor-aware parts.</summary>
        public ArmorPartOverride[] partOverrides = Array.Empty<ArmorPartOverride>();

        /// <summary>
        /// Head sub-part slot names hidden by this armor (e.g. some armors remove forelock, eye, horn).
        /// Null or empty means all default head sub-parts are visible.
        /// </summary>
        public string[] hiddenHeadParts;
    }

    /// <summary>
    /// Armor sprite override for a single body part.
    /// </summary>
    [Serializable]
    public struct ArmorPartOverride
    {
        /// <summary>Index into CharacterAnimationDefinition.parts array.</summary>
        public int partIndex;

        /// <summary>Sprite to use when this armor is equipped.</summary>
        public Sprite armorSprite;

        /// <summary>
        /// Pivot override for this armor sprite (normalized 0-1).
        /// For body parts this matches the default part pivot.
        /// For head sub-part variants (different symbol), this is the variant symbol's pivot.
        /// </summary>
        public Vector2 pivotOverride;

        /// <summary>
        /// Position offset in Unity coordinates (Y-up) to apply when rendering this armor sprite.
        /// Accounts for sub-parts being repositioned in per-armor morda_armor(273) frames.
        /// Zero for body parts and head sub-parts that aren't repositioned.
        /// </summary>
        public Vector2 positionOffset;
    }

    public enum AnimationLoopMode
    {
        Loop,           // Play and loop (default for most states)
        ClampForever,   // Play once and hold last frame (die, res)
        Manual,         // Frame controlled by code (ladder, stay poses)
        LoopRange,      // Loop a sub-range (jump loops 11-25, levit loops sections)
    }

    /// <summary>
    /// Tint category for character creation color channels.
    /// Matches AS3 Obj.setColor() categories.
    /// </summary>
    public enum TintCategory
    {
        None = -1,
        Fur = 0,
        Hair = 1,
        Hair2 = 2,
        Eye = 3,
        Magic = 4,
    }
}
