using System;
using UnityEngine;

namespace PFE.Data.Definitions
{
    /// <summary>
    /// ScriptableObject containing all visual data needed to render the main menu background.
    /// Generated by the MainMenu SWF import pipeline from assets.swf symbol 559 (visMainMenu).
    /// Consumed at runtime by MainMenuBackgroundRenderer.
    /// </summary>
    [CreateAssetMenu(fileName = "MainMenuComposition", menuName = "PFE/Main Menu Composition")]
    public class MainMenuCompositionDefinition : ScriptableObject
    {
        [Header("Background Layers (back to front)")]
        [Tooltip("Sky/clouds layer — shape 411, 1920x565")]
        public Sprite sky;
        public Vector2 skyPosition;

        [Tooltip("City scene with baked pony body — shape 425, 1920x926")]
        public Sprite cityScene;
        public Vector2 cityScenePosition;

        [Tooltip("FALLOUT EQUESTRIA REMAINS logo — shape 471, 641x249")]
        public Sprite logo;
        public Vector2 logoPosition;

        [Header("Pipka — Animated Foreground")]
        [Tooltip("Position of pipka root in Flash coordinates (Y-down, pixels)")]
        public Vector2 pipkaPosition = new(670f, 360f);

        [Tooltip("Horn tip piece — shape 437, 54x93")]
        public Sprite hornPiece;
        public Vector2 hornPieceLocalPos;

        [Tooltip("Ear/body piece — shape 455, 42x63")]
        public Sprite earPiece;
        public Vector2 earPieceLocalPos;

        [Header("Pipka — Eye Blink")]
        [Tooltip("Eye blink frames (5 frames: open → half → closed → half → open)")]
        public Sprite[] eyeFrames = Array.Empty<Sprite>();
        public Vector2 eyeLocalPos = new(77.5f, 97.5f);

        [Header("Pipka — Displacement Targets")]
        [Tooltip("Mane layer for displacement distortion — shape 434, 240x300")]
        public Sprite displacementMane;
        public Vector2 displacementManeLocalPos;

        [Tooltip("Tail layer for displacement distortion — shape 451, 240x300")]
        public Sprite displacementTail;
        public Vector2 displacementTailLocalPos;

        [Header("Pipka — Horn")]
        public Vector2 hornLocalPos = new(52f, 55.1f);

        [Tooltip("Horn magic glow backdrop — shape 441, 220x220")]
        public Sprite hornMagicGlow;

        [Tooltip("Magic circle (shared by all krug instances) — shape 443, 200x200")]
        public Sprite magicKrug;

        [Tooltip("Horn krug initial scale")]
        public float hornKrugScale = 0.58f;

        [Tooltip("Horn spark frames (50 frames)")]
        public Sprite[] hornSparkFrames = Array.Empty<Sprite>();

        [Tooltip("Horn spark instance positions (local to horn)")]
        public SparkInstance[] hornSparkInstances = Array.Empty<SparkInstance>();

        [Header("Pipka — Pistol")]
        public Vector2 pistolLocalPos = new(-19f, 86.1f);

        [Tooltip("Pistol body — shape 457, 40x98")]
        public Sprite pistolBody;

        [Tooltip("Pistol body detail layer (rendered behind main body)")]
        public Sprite pistolDetail;

        [Tooltip("Pistol magic glow — shape 462, 220x220")]
        public Sprite pistolMagicGlow;

        [Tooltip("Pistol magic2 glow — shape 465, 220x220")]
        public Sprite pistolMagic2Glow;

        [Tooltip("Pistol spark frames (50 frames)")]
        public Sprite[] pistolSparkFrames = Array.Empty<Sprite>();

        [Tooltip("Pistol spark instance positions (local to pistol)")]
        public SparkInstance[] pistolSparkInstances = Array.Empty<SparkInstance>();

        [Header("Storm — Lightning (groza)")]
        [Tooltip("Default groza position in Flash coordinates")]
        public Vector2 grozaDefaultPos = new(1012.2f, -409f);

        [Tooltip("Storm cloud texture — shape 415, 800x544, screen blend")]
        public Sprite lightningClouds;
        public Vector2 lightningCloudsLocalPos;

        [Tooltip("Lightning bolt frames (4 variants)")]
        public Sprite[] lightningBoltFrames = Array.Empty<Sprite>();

        [Tooltip("Bolt (moln) local position within groza group")]
        public Vector2 lightningBoltLocalPos;

        [Tooltip("Cloud mask rect in groza-local Flash coords (for clipping visible cloud area)")]
        public Rect lightningMaskRect;

        [Header("Animation Parameters (from Displ.as)")]
        [Tooltip("Game runs at 30 FPS")]
        public float frameRate = 30f;

        [Tooltip("Eye blink interval range in seconds")]
        public float blinkIntervalMin = 2f;
        public float blinkIntervalMax = 5.67f;

        [Tooltip("Pistol bob: x = base + sin(t/speed) * ampX")]
        public float pistolBobSpeed = 100f;
        public float pistolBobAmplitudeX = 2f;
        public float pistolBobAmplitudeY = 8f;

        [Tooltip("Magic krug rotation speeds (degrees per frame at 30fps)")]
        public float magicRotSpeed1 = 1f;
        public float magicRotSpeed2 = 0.67f;

        [Tooltip("Lightning spawn interval range in seconds")]
        public float lightningIntervalMin = 3.33f;
        public float lightningIntervalMax = 10f;

        [Tooltip("Lightning visible burst duration in frames")]
        public int lightningBurstFrames = 30;

        [Tooltip("Lightning spawn area (Flash coords)")]
        public float lightningSpawnWidth = 1800f;
        public float lightningSpawnHeight = 350f;
    }

    /// <summary>
    /// Position data for a single spark particle instance.
    /// Multiple instances of the same spark animation are placed at different offsets.
    /// </summary>
    [Serializable]
    public struct SparkInstance
    {
        public Vector2 localPosition;

        public SparkInstance(Vector2 pos)
        {
            localPosition = pos;
        }
    }
}
