using System;
using System.Collections.Generic;
using UnityEngine;

namespace PFE.Systems.Audio
{
    /// <summary>
    /// Maps logical sound IDs (from Snd.as) to AudioClips.
    /// Generated by the SoundImporter editor tool.
    /// Groups (rm, rw, fang_hit, etc.) have multiple variants — a random one is picked at runtime.
    ///
    /// Asset location: Assets/_PFE/Data/SoundCatalog.asset
    /// </summary>
    [CreateAssetMenu(fileName = "SoundCatalog", menuName = "PFE/Sound Catalog")]
    public class SoundCatalog : ScriptableObject
    {
        [Serializable]
        public class Entry
        {
            [Tooltip("Logical ID matching Snd.as declaration (e.g. 'rifle_s', 'rm', 'fang_hit')")]
            public string id;

            [Tooltip("One or more clips. Multiple = random group (rm1..rm6, fang_hit1..3, etc.)")]
            public AudioClip[] variants;

            [Tooltip("Source library: sound | sound_weapon | sound_unit")]
            public string library;
        }

        public List<Entry> entries = new List<Entry>();

        // --- Runtime lookup (built once on first access) ---
        private Dictionary<string, Entry> _map;

        private void BuildMap()
        {
            _map = new Dictionary<string, Entry>(entries.Count, StringComparer.OrdinalIgnoreCase);
            foreach (var e in entries)
            {
                if (!string.IsNullOrEmpty(e.id))
                    _map[e.id] = e;
            }
        }

        public bool TryGet(string id, out Entry entry)
        {
            if (_map == null) BuildMap();
            return _map.TryGetValue(id, out entry);
        }

        /// <summary>Called by the importer after modifying entries in the editor.</summary>
        public void InvalidateCache() => _map = null;
    }
}
